language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - libgtest-dev

before_install:
    - mkdir cmake_build
    - cd cmake_build
    - cmake /usr/src/gtest
    - cd ..

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
