language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
      - cmake-data
      - libgtest-dev

before_script:
    - export CXX=/usr/bin/g++-5
    - export CC=/usr/bin/gcc-5

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make tests
