language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
      - cmake-data
      - libgtest-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
