language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - google-mock
      - libgtest-dev

script:
    - cmake .
    - make
