language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
      - cmake-data
      - libgtest-dev
      - libboost-dev
      - libssl-dev

before_script:
    - export CXX=/usr/bin/g++-7
    - export CC=/usr/bin/gcc-7

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
