language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - libgtest-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
